In [4]:
print("Hello World!")

Hello World!


1. int - positive and negative whole numbers
2. float - postive and negative decimal values
3. str - anything inside single/double quotes
4. bool - True/False

In [5]:
num = 12
print(type(num))

<class 'int'>


In [7]:
num = "12.2"
print(type(num))

<class 'str'>


In [15]:
num1 = int(input("Enter first number")) #2
num2 = int(input("Enter second number")) #3

print("The sum of", num1, "and", num2, "is", num1+num2)

Enter first number 2
Enter second number 3


The sum of 2 and 3 is 5


The sum of 2 and 3 is 5.

In [16]:
# using f-string
print(f"The sum of {num1} and {num2} is {num1+num2}.")

The sum of 2 and 3 is 5.


## Write a program to ask for the name, age and a boolean likesTea from the user and print a sentence,

`{name} is {age} years old and it is {likesTea} that {name} likes Tea.`

## Also print the year of birth of the user.

In [18]:
name = input("Enter your name:")
age = int(input("Enter your age:"))
likesTea = input("You like Tea?!")

print(f"{name} is {age} years old and it is {likesTea} that {name} likes Tea.")
print(f"{name} was born in {2025-age}")

Enter your name: Ram
Enter your age: 1
You like Tea?! False


Ram is 1 years old and it is False that Ram likes Tea.
Ram was born in 2024


## `iterable`
## `iterate`

`[start:stop:step]`

## create a List of names.

In [40]:
names = ["Ram", "shyam", "Hari"]
print(type(names))

<class 'list'>


## Adding a value to the end of the list.

`.append()`

In [41]:
names.append("Madhav")
print(names)

['Ram', 'shyam', 'Hari', 'Madhav']


In [42]:
print(names)

['Ram', 'shyam', 'Hari', 'Madhav']


In [43]:
names.pop()

'Madhav'

In [44]:
print(names)

['Ram', 'shyam', 'Hari']


In [46]:
names.remove("Hari")

In [47]:
print(names)

['Ram', 'shyam']


In [48]:
names = ['Ram', 'shyam', 'Hari', 'Madhav']
names.pop(1)

'shyam'

In [49]:
print(names)

['Ram', 'Hari', 'Madhav']


In [51]:
names.index("Hari")

1

In [52]:
names = ['Ram', 'shyam', 'Hari', 'Madhav']
names[0] = "Ramesh"
print(names)

['Ramesh', 'shyam', 'Hari', 'Madhav']


In [54]:
names = ('Ram', 'shyam', 'Hari', 'Madhav')
names = list(names)
names

['Ram', 'shyam', 'Hari', 'Madhav']

In [57]:
names.append("Rita")

In [58]:
tuple(names)

('Ram', 'shyam', 'Hari', 'Madhav', 'Rita', 'Rita')

In [59]:
names.count("Rita")

2

### Create a dictionary with name, age as keys and names and ages as values.

In [60]:
info = {"name": ["Ram", "Shyam"],
       "age":[23, 24]}

In [61]:
detail = {"name": "ram",
         "age": 23}

In [62]:
info = {"name": ("Ram", "Shyam"),
       "age":[23, 24]}

In [63]:
info['name']

('Ram', 'Shyam')

In [64]:
info['age']

[23, 24]

In [65]:
info.keys()

dict_keys(['name', 'age'])

In [66]:
info.values()

dict_values([('Ram', 'Shyam'), [23, 24]])

In [68]:
info.items()

dict_items([('name', ('Ram', 'Shyam')), ('age', [23, 24])])

In [69]:
nums = {1,1,2,3}
print(nums)

{1, 2, 3}


In [70]:
nums = [1,1,2,3]
print(nums)

[1, 1, 2, 3]


## Create a dictionary of yourself. 
- keys : name, age, fav_foods


In [71]:
my_info = {"name" : "Kiran",
          "age" : 25,
          "fav_foods" : ["momo", "pizza"]}

In [74]:
my_info['fav_foods'].append("rice")

In [75]:
my_info

{'name': 'Kiran', 'age': 25, 'fav_foods': ['momo', 'pizza', 'rice']}

## Add a new key address to the dictionary. 

In [76]:
my_info['Address'] = "Patan"

In [77]:
my_info

{'name': 'Kiran',
 'age': 25,
 'fav_foods': ['momo', 'pizza', 'rice'],
 'Address': 'Patan'}

## Python For Loop Syntax

In [81]:
list(range(0, 11, 2))

[0, 2, 4, 6, 8, 10]

In [82]:
## generate odd numbers between 0 and 15 using range function
list(range(1, 15, 2))

[1, 3, 5, 7, 9, 11, 13]

In [86]:
## 11 to 0 
list(range(11, -1, -1))

[11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [87]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [89]:
for i in range(5):
    print(i)

0
1
2
3
4


In [90]:
for i in [0, 1, 2, 3, 4, 5]:
    print(i)

0
1
2
3
4
5


In [93]:
for names in ["ram", "shyam"]:
    print(names)

ram
shyam


In [94]:
i = 0 
while i < 5:
    print("Hello")
    i = i + 1

Hello
Hello
Hello
Hello
Hello


## For a list nums = [1, 2, 3, 4, 5], print the cubes of all the numbers.

In [100]:
nums = [1, 2, 3, 4, 5]
for number in nums:
    print(number**3)

1
8
27
64
125


## For a list nums = [1, 2, 3, 4, 5], create a new list with cube of all the numbers.

In [103]:
nums = [1, 2, 3, 4, 5]
cubes = []
for number in nums:
    cubes.append(number**3)
    # print(number, cubes)

print(cubes)

[1, 8, 27, 64, 125]


```
def funcName():
        ...
        ...
```

In [114]:
## defining the function
def addition(num1, num2):
    total = num1 + num2
    return(total)

In [115]:
# calling the function
print(addition(1, 2))

3


# Revision

In [ ]:
a = 10
b = a
a = 20
print(b)

## Create a list of 5 integers. Remove the third element and print the new list.

In [1]:
nums  = [1, 2, 3, 4, 5]
nums.pop(2)

3

In [2]:
print(nums)

[1, 2, 4, 5]


## Reverse a list without using reverse() or slicing. 

In [4]:
nums

[1, 2, 4, 5]

In [5]:
nums[::-1]

[5, 4, 2, 1]

`range()`, `for`

In [4]:
nums  = [1, 2, 3, 4, 5]
rev_nums = []
for i in range(len(nums)-1, -1, -1):
    rev_nums.append(nums[i])
print(rev_nums)

[5, 4, 3, 2, 1]


## Given a list of numbers, create a new list that contains only the even numbers.

In [5]:
numbers = [23, 34, 56, 57, 89, 90]
even_nums = []
for number in numbers:
    if number%2==0:
        even_nums.append(number)
print(even_nums)

[34, 56, 90]


In [6]:
print = "Ram"

In [7]:
print(print)

TypeError: 'str' object is not callable

## Create a dictionary for 3 students. Each student should have a name and a single total_marks value. Find and print the name of the student with the highest marks.

In [15]:
students = {"Ram" : 80,
           "Shyam" : 90,
           "Ramesh": 93,
           "Kumar": 56}

highest_score = 0
highest_score_name = ""
for name in students:
    if students[name] > highest_score:
        highest_score = students[name]
        highest_score_name = name

print(f"The student with the highest score of {highest_score} is {highest_score_name}.")

The student with the highest score of 93 is Ramesh.


## Create a dictionary of items and prices. Increase all prices by 10% and print the updated dictionary.

In [21]:
grocery = {"apple" : 100,
          "banana" : 60}

updated_grocery = {}

In [22]:
for item in grocery:
    updated_grocery[item] = grocery[item] * 1.1

print(updated_grocery)

{'apple': 110.00000000000001, 'banana': 66.0}


## Conver the following lists into a dictionary that maps name -> age.
### names = ['Manu', 'Sita', 'Raju']
### ages = [28, 20, 25]

In [24]:
names = ['Manu', 'Sita', 'Raju']
ages = [28, 20, 25]

details = {}

for i in range(len(names)):
    details[names[i]] = ages[i]

print(details)

{'Manu': 28, 'Sita': 20, 'Raju': 25}


## Print the sum of all even numbers between 1 and 100.

In [25]:
total = 0
for i in range(1, 101):
    if i%2 == 0:
        total += i
print(total)

2550


## Count how many vowels are in a given word.

In [28]:
word = input("Enter a word").lower()

count = 0

for letter in word:
    if letter in "aeiou":
        count += 1

print(count)

Enter a word Apple


2


## Write a function `merge_dicts(d1, d2)` that merges two dictionaries and returns the result.

In [33]:
d1 = {"a" : 1, "b" : 2}
d2 = {"c" : 3, "d" : 4}

def merge_dicts(d1, d2):
    for k in d1:
        d2[k] = d1[k]
    return d2

merge_dicts(d1, d2)

{'c': 3, 'd': 4, 'a': 1, 'b': 2}

### For two lists, `nums1 = [1, 2, 3, 4, 5]` and `nums2 = [6, 7, 8, 9, 0]`
### print a list which has element wise sum of the numbers in the lists.

In [34]:
nums1 = [1, 2, 3, 4, 5]
nums2 = [6, 7, 8, 9, 0]

# nums3 = [7, 9, 11, 13, 5]
total = []

for i in range(len(nums1)):
    total.append(nums1[i] + nums2[i])

print(total)

[7, 9, 11, 13, 5]


In [35]:
import numpy as np

nums1 = np.array([1, 2, 3, 4, 5])
nums2 = np.array([6, 7, 8, 9, 0])

print(nums1+nums2)

[ 7  9 11 13  5]


# Python Lists vs NumPy

In [36]:
import time
import numpy as np

n = 10000000

py_list1 = list(range(n))
py_list2 = list(range(n))

start = time.perf_counter()
py_result = [a * b for a, b in zip(py_list1, py_list2)]
end = time.perf_counter()
print(f"Python list time: {end - start:.5f} seconds")

np_array1 = np.arange(n)
np_array2 = np.arange(n)

start = time.perf_counter()
np_result = np_array1 * np_array2
end = time.perf_counter()
print(f"NumPy array time: {end - start:.5f} seconds")


Python list time: 1.58914 seconds
NumPy array time: 0.02291 seconds


In [49]:
array1 = np.array([1, 2, 3])
print(type(array1), array1.ndim, array1.shape)

<class 'numpy.ndarray'> 1 (3,)


### Arrays of zeros

In [50]:
array2 = np.zeros((3,3,3))
print(array2, array2.ndim, array2.shape)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]] 3 (3, 3, 3)


In [45]:
print(array2.ndim)

3


In [51]:
ones_array = np.ones((3,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [53]:
np.arange(0, 101, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [55]:
val = np.linspace(0, 1, 10)
print(val)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


## Create a 1D numpy array of 20 numbers between 0 and 10(inclusive) using `linspace()`.

In [56]:
np.linspace(0, 11, 20)

array([ 0.        ,  0.57894737,  1.15789474,  1.73684211,  2.31578947,
        2.89473684,  3.47368421,  4.05263158,  4.63157895,  5.21052632,
        5.78947368,  6.36842105,  6.94736842,  7.52631579,  8.10526316,
        8.68421053,  9.26315789,  9.84210526, 10.42105263, 11.        ])

In [57]:
array1 = np.arange(1, 21)

In [58]:
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [62]:
array1.reshape((1,2,2,5, 1))

array([[[[[ 1],
          [ 2],
          [ 3],
          [ 4],
          [ 5]],

         [[ 6],
          [ 7],
          [ 8],
          [ 9],
          [10]]],


        [[[11],
          [12],
          [13],
          [14],
          [15]],

         [[16],
          [17],
          [18],
          [19],
          [20]]]]])

## Create a 3X3 NumPy array containing the numbers between 1 to 9.